[package]
name = "shade-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shade-rs-core = { path = "../shade-rs-core" }
shade-rs-macros = { path = "../shade-rs-macros" }
